package recyclapp.gui;

import application.Controller;
import domaine.EntreeUsine;
import java.awt.BorderLayout;

import javax.swing.JTable;

public class FenetrePanierProduit extends javax.swing.JFrame {
    private final JTable tableau;
    private final EntreeUsine entree;
    private final Controller controller;
    
    
    /**
     * Creates new form FenetrePanierProduit
     * @param entree
     * @param controller
     */
    //@SuppressWarnings("empty-statement")
    public FenetrePanierProduit(EntreeUsine entree,Controller controller) {
        initComponents();
        this.entree = entree;
        this.controller = controller;
        
        
        String[] colonnes = new String[2];
        colonnes[0] = "Produits";
        colonnes[1] = "Taux d'arrivée (Kg)";        
        tableau = new JTable(entree.produits, colonnes);
        
        
        this.setLayout(new BorderLayout());
        this.add(tableau.getTableHeader(), BorderLayout.PAGE_START);
        this.add(tableau, BorderLayout.CENTER);
        this.setVisible(true);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnregistrer = new javax.swing.JButton();
        btnAjouterLigne = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        btnAjouterLigne.setText("Nouvelle ligne");
        btnAjouterLigne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterLigneActionPerformed(evt);
            }
        });

        jButton1.setText("Supprimer selection");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAjouterLigne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(btnEnregistrer)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnregistrer)
                    .addComponent(btnAjouterLigne)
                    .addComponent(jButton1))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed

        // TODO : enregistrer les modifications apportées
        //DefaultTableModel dtm = (DefaultTableModel) tableau.getModel();
        int nRow = tableau.getRowCount(), nCol = tableau.getColumnCount();
        Object[][] tableData = new Object[nRow][nCol];
        for (int i = 0 ; i < nRow ; i++) 
        {
            for (int j = 0 ; j < nCol ; j++)
                tableData[i][j] = tableau.getValueAt(i,j);
        }
            
        entree.modifierProduits(tableData);
        controller.MettreAJourQuantiteTous();

    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void btnAjouterLigneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterLigneActionPerformed
        
        // TODO : ajouter une nouvelle ligne au tableau des produits
    }//GEN-LAST:event_btnAjouterLigneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        // TODO : supprimer les listes selectionnées et actualiser l'affichage
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterLigne;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
