package recyclapp.gui;

import application.Controller;
import domaine.Station;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JTable;

public class FenetreMatriceTransformation extends javax.swing.JFrame {
    private JTable tableau;
    private Station station;
    private Controller controller;
    /**
     * Creates new form FenetreMatriceTransformation
     */
    @SuppressWarnings("empty-statement")
    public FenetreMatriceTransformation(Station station,Controller controller) {
        initComponents();
        this.station = station;
        this.controller = controller;
        String[] colonnes = new String[station.nombreSorties + 1];
        colonnes[0] = "Produits";
        for(int i = 1;i<=station.nombreSorties;i++)
        {
            colonnes[i] = "Sortie " + i;
        }       
        
                
        tableau = new JTable(station.produits, colonnes);
        this.setLayout(new BorderLayout());
        this.add(tableau.getTableHeader(), BorderLayout.PAGE_START);
        this.add(tableau, BorderLayout.CENTER);
        this.setVisible(true);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnregistrer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(btnEnregistrer)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(btnEnregistrer)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        //DefaultTableModel dtm = (DefaultTableModel) tableau.getModel();
        int nRow = tableau.getRowCount(), nCol = tableau.getColumnCount();
        Object[][] tableData = new Object[nRow][nCol];
        for (int i = 0 ; i < nRow ; i++)
            for (int j = 0 ; j < nCol ; j++)
                tableData[i][j] = tableau.getValueAt(i,j);
        if(!validerMatrice(tableData))
        {
            JOptionPane.showMessageDialog(this, "Le pourcentage pour la somme de chaque matière doit égaler 100%");
        }
        else
        {
            station.produits = tableData;
            controller.MettreAJourQuantiteTous();
        }
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private boolean validerMatrice(Object[][] tableData)
    {
        for(int i=0;i<tableData.length;i++)
        {
            int total =0;
            for(int j=1; j<tableData[i].length;j++)
            {
                total += Integer.parseInt(tableData[i][j].toString());
            }
            if(total != 100)
                return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnregistrer;
    // End of variables declaration//GEN-END:variables
}
