package recyclapp.gui;
import application.Controller;
import javax.swing.ImageIcon;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import utilitaires.Coordonnee;



/**
 *
 * @author De Bayzer
 */
public class FenetrePrincipale extends javax.swing.JFrame{
    
    
//    private final InterfacePlan interfacePlan;
    private final Controller controller;
    private final PanneauSelectionStation panneauSelectionStation ;
    
    public final PanneauPlanTravail panneauPlanTravailExt;
    
    private boolean dansLePlan = false; //Si le curseur est présentement à l'intérieur du plan

    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() 
    {
        initComponents();
        controller = new Controller();
        panneauSelectionStation = new PanneauSelectionStation(this.panneauProprietes ,controller);
        panneauSelectionStation.Init();
        
        panneauPlanTravailExt = new PanneauPlanTravail(this.panneauPlanTravail, controller, panneauSelectionStation);
        panneauPlanTravailExt.Init();

        controller.ajouterEntreeUsine(new Coordonnee(420-38,300-38));
        panneauPlanTravailExt.RafraichirPlan();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupeAffichage = new javax.swing.ButtonGroup();
        panneauMenuHaut = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panneauOutils = new javax.swing.JPanel();
        btnAjoutConvoyeur = new javax.swing.JButton();
        btnStation = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnJonction = new javax.swing.JButton();
        btnSortieUsine = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panneauProprietes = new javax.swing.JPanel();
        panneauPlanTravail = new javax.swing.JPanel();
        panneauMenuBas = new javax.swing.JPanel();
        labelCoordonnees = new javax.swing.JLabel();
        checkboxGrilleMagnetique = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        textPanelCoordonnees = new javax.swing.JTextPane();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        echelle = new javax.swing.JComboBox();
        checkboxGrille = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RecyclApp - Troyens");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        panneauMenuHaut.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "menu haut [x]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/light/save.png"))); // NOI18N
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/light/appbar.folder.open.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/light/appbar.undo.curve.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(75, 75));
        jLabel4.setPreferredSize(new java.awt.Dimension(75, 75));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/light/appbar.redo.curve.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(new java.awt.Dimension(75, 75));
        jLabel5.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel5.setPreferredSize(new java.awt.Dimension(75, 75));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/light/appbar.delete.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setMaximumSize(new java.awt.Dimension(75, 75));
        jLabel6.setMinimumSize(new java.awt.Dimension(75, 75));
        jLabel6.setPreferredSize(new java.awt.Dimension(75, 75));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/light/appbar.check.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(75, 75));
        jLabel7.setMinimumSize(new java.awt.Dimension(75, 75));
        jLabel7.setPreferredSize(new java.awt.Dimension(75, 75));

        ImageIcon iconeEnregistrer = new ImageIcon("save.png");
        jLabel2.setIcon(iconeEnregistrer);

        javax.swing.GroupLayout panneauMenuHautLayout = new javax.swing.GroupLayout(panneauMenuHaut);
        panneauMenuHaut.setLayout(panneauMenuHautLayout);
        panneauMenuHautLayout.setHorizontalGroup(
            panneauMenuHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauMenuHautLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(810, Short.MAX_VALUE))
        );
        panneauMenuHautLayout.setVerticalGroup(
            panneauMenuHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauMenuHautLayout.createSequentialGroup()
                .addGroup(panneauMenuHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panneauMenuHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panneauMenuHautLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        panneauOutils.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "outils", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        panneauOutils.setToolTipText("");

        btnAjoutConvoyeur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/light/appbar.vector.line.png"))); // NOI18N
        btnAjoutConvoyeur.setToolTipText("");
        btnAjoutConvoyeur.setEnabled(false);
        btnAjoutConvoyeur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjoutConvoyeurMouseClicked(evt);
            }
        });

        btnStation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/station3moyen.png"))); // NOI18N
        btnStation.setToolTipText("");
        btnStation.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnStation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnStationMouseReleased(evt);
            }
        });

        jLabel8.setText("Station");

        btnJonction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/jonction.png"))); // NOI18N
        btnJonction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJonction.setEnabled(false);
        btnJonction.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnJonctionMouseDragged(evt);
            }
        });
        btnJonction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnJonctionMouseReleased(evt);
            }
        });

        btnSortieUsine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/light/appbar.door.leave.png"))); // NOI18N
        btnSortieUsine.setToolTipText("");
        btnSortieUsine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSortieUsine.setEnabled(false);
        btnSortieUsine.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnSortieUsineMouseDragged(evt);
            }
        });
        btnSortieUsine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSortieUsineMouseReleased(evt);
            }
        });

        jLabel9.setText("sortie d' usine");

        jLabel10.setText("Jonction");

        jLabel11.setText("Convoyeur");

        javax.swing.GroupLayout panneauOutilsLayout = new javax.swing.GroupLayout(panneauOutils);
        panneauOutils.setLayout(panneauOutilsLayout);
        panneauOutilsLayout.setHorizontalGroup(
            panneauOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauOutilsLayout.createSequentialGroup()
                .addGroup(panneauOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panneauOutilsLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(panneauOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(btnStation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauOutilsLayout.createSequentialGroup()
                        .addContainerGap(65, Short.MAX_VALUE)
                        .addGroup(panneauOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(btnAjoutConvoyeur, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)))
                .addGroup(panneauOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauOutilsLayout.createSequentialGroup()
                        .addGroup(panneauOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnJonction, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSortieUsine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauOutilsLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(84, 84, 84))))
        );
        panneauOutilsLayout.setVerticalGroup(
            panneauOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauOutilsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panneauOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnStation, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSortieUsine, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panneauOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(panneauOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAjoutConvoyeur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJonction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panneauOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(23, 23, 23))
        );

        panneauProprietes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "propriétés", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        panneauProprietes.setMaximumSize(new java.awt.Dimension(327, 332));
        panneauProprietes.setMinimumSize(new java.awt.Dimension(327, 332));
        panneauProprietes.setPreferredSize(new java.awt.Dimension(327, 332));

        javax.swing.GroupLayout panneauProprietesLayout = new javax.swing.GroupLayout(panneauProprietes);
        panneauProprietes.setLayout(panneauProprietesLayout);
        panneauProprietesLayout.setHorizontalGroup(
            panneauProprietesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panneauProprietesLayout.setVerticalGroup(
            panneauProprietesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panneauPlanTravail.setBackground(new java.awt.Color(153, 153, 153));
        panneauPlanTravail.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "plan de travail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        panneauPlanTravail.setForeground(new java.awt.Color(255, 255, 255));
        panneauPlanTravail.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panneauPlanTravailMouseMoved(evt);
            }
        });
        panneauPlanTravail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panneauPlanTravailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panneauPlanTravailMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panneauPlanTravailLayout = new javax.swing.GroupLayout(panneauPlanTravail);
        panneauPlanTravail.setLayout(panneauPlanTravailLayout);
        panneauPlanTravailLayout.setHorizontalGroup(
            panneauPlanTravailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        panneauPlanTravailLayout.setVerticalGroup(
            panneauPlanTravailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        panneauMenuBas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        labelCoordonnees.setText("Coordonnées :");

        checkboxGrilleMagnetique.setText("Grille magnétique");

        textPanelCoordonnees.setEditable(false);
        textPanelCoordonnees.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jScrollPane2.setViewportView(textPanelCoordonnees);

        groupeAffichage.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Affichage image");

        groupeAffichage.add(jRadioButton2);
        jRadioButton2.setText("Affichage texte");

        jLabel1.setText("Échelle :");

        echelle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 m", "2 m", "4 m", "10 m" }));
        echelle.setSelectedIndex(2);
        echelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                echelleActionPerformed(evt);
            }
        });

        checkboxGrille.setSelected(true);
        checkboxGrille.setText("Grille");
        checkboxGrille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxGrilleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panneauMenuBasLayout = new javax.swing.GroupLayout(panneauMenuBas);
        panneauMenuBas.setLayout(panneauMenuBasLayout);
        panneauMenuBasLayout.setHorizontalGroup(
            panneauMenuBasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauMenuBasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCoordonnees)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addGroup(panneauMenuBasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panneauMenuBasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkboxGrille)
                    .addComponent(checkboxGrilleMagnetique))
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(echelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panneauMenuBasLayout.setVerticalGroup(
            panneauMenuBasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauMenuBasLayout.createSequentialGroup()
                .addGroup(panneauMenuBasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panneauMenuBasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(checkboxGrille)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(panneauMenuBasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panneauMenuBasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(checkboxGrilleMagnetique)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauMenuBasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panneauMenuBasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauMenuBasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCoordonnees))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauMenuBasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(echelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panneauMenuHaut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panneauProprietes, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(panneauOutils, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panneauMenuBas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panneauPlanTravail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panneauMenuHaut, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panneauOutils, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panneauProprietes, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panneauPlanTravail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panneauMenuBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panneauPlanTravailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panneauPlanTravailMouseEntered
        dansLePlan = true;
    }//GEN-LAST:event_panneauPlanTravailMouseEntered

    private void panneauPlanTravailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panneauPlanTravailMouseExited
        dansLePlan = false;
    }//GEN-LAST:event_panneauPlanTravailMouseExited

    private void btnStationMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStationMouseReleased
        if(dansLePlan)
        {
            Coordonnee coord = new Coordonnee(evt.getX()-330 ,evt.getY());
        
            JFrame frame = new JFrame("Entrez coordonnées");
            String QteSorties = JOptionPane.showInputDialog(frame,"Nombre de sorties :");
            int nombreSorties = Integer.parseInt(QteSorties);
                
            controller.ajouterStation(coord, nombreSorties ); 
            panneauPlanTravailExt.RafraichirPlan();
        }
    }//GEN-LAST:event_btnStationMouseReleased

    private void btnAjoutConvoyeurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjoutConvoyeurMouseClicked
        btnAjoutConvoyeur.setFont(btnAjoutConvoyeur.getFont().deriveFont(Font.BOLD));
        controller.btnAjoutConvoyeurClicked = true;
    }//GEN-LAST:event_btnAjoutConvoyeurMouseClicked

    private void btnJonctionMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJonctionMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJonctionMouseDragged

    private void btnJonctionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJonctionMouseReleased
        if(dansLePlan)
        {
            Coordonnee coord = new Coordonnee(evt.getX()- 170 ,evt.getY()+ 100);
            controller.ajouterJonction(coord ); 
            panneauPlanTravailExt.RafraichirPlan();
        }
    }//GEN-LAST:event_btnJonctionMouseReleased

    private void btnSortieUsineMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSortieUsineMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSortieUsineMouseDragged

    private void btnSortieUsineMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSortieUsineMouseReleased
        if(dansLePlan)
        {
            Coordonnee coord = new Coordonnee(evt.getX()-190 ,evt.getY());
            controller.ajouterSortieUsine(coord ); 
            panneauPlanTravailExt.RafraichirPlan();
        }
    }//GEN-LAST:event_btnSortieUsineMouseReleased

    private void checkboxGrilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxGrilleActionPerformed
        checkboxGrilleMagnetique.setEnabled(checkboxGrille.isSelected());
        panneauPlanTravailExt.grille = checkboxGrille.isSelected();
        panneauPlanTravailExt.RafraichirPlan();
    }//GEN-LAST:event_checkboxGrilleActionPerformed

    private void echelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_echelleActionPerformed
        controller.plan.zoom = echelle.getSelectedIndex();
        panneauPlanTravailExt.RafraichirPlan();
    }//GEN-LAST:event_echelleActionPerformed

    private void panneauPlanTravailMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panneauPlanTravailMouseMoved
        Coordonnee coord = controller.plan.coordonneeCliqueSurPlan(new Coordonnee(evt.getX(),evt.getY()));
        int zoom = controller.plan.zoom_values[controller.plan.zoom];
        textPanelCoordonnees.setText("x:"+coord.getX()*zoom/40+"m\ny:"+coord.getY()*zoom/40+"m");
    }//GEN-LAST:event_panneauPlanTravailMouseMoved

       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjoutConvoyeur;
    private javax.swing.JButton btnJonction;
    private javax.swing.JButton btnSortieUsine;
    private javax.swing.JLabel btnStation;
    private javax.swing.JCheckBox checkboxGrille;
    private javax.swing.JCheckBox checkboxGrilleMagnetique;
    private javax.swing.JComboBox echelle;
    private javax.swing.ButtonGroup groupeAffichage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCoordonnees;
    private javax.swing.JPanel panneauMenuBas;
    private javax.swing.JPanel panneauMenuHaut;
    private javax.swing.JPanel panneauOutils;
    private javax.swing.JPanel panneauPlanTravail;
    private javax.swing.JPanel panneauProprietes;
    private javax.swing.JTextPane textPanelCoordonnees;
    // End of variables declaration//GEN-END:variables

    

}
