package recyclapp.gui;

import application.*;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;
import utilitaires.*;
import domaine.*;
import java.awt.Color;

import java.awt.BasicStroke;

/**
 *
 * @author De Bayzer
 */
public class PanneauPlanTravail extends javax.swing.JPanel {
    
    private final JPanel conteneur ;
    private final Controller controller;
    public java.util.ArrayList<CoordonneeLigne> listeCoordonnees = new java.util.ArrayList();

    /**
     * Creates new form PanneauPlanTravail
     * @param unConteneur
     * @param unController
     */
    public PanneauPlanTravail(JPanel unConteneur, Controller unController) {
        conteneur = unConteneur ;
        controller = unController ;
        initComponents();
    }
    
    public void Init()
    {
        this.setLocation(0,0);
        this.setSize(this.conteneur.getSize());
        this.conteneur.add(this);
        initComponents();
        this.conteneur.repaint();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Plan de travail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    @Override
    public void paint (Graphics g)
    {
        super.paint(g);
        afficherConvoyeurs(g);
        //afficherStations();
    }
    
    private void afficherConvoyeurs(Graphics g)
    {
        
        // on stocke les coordonnées des lignes a tracer dans une arrayliste
        for (int i= 0; i< this.controller.plan.listeConvoyeur.size(); i++ )
        {
            this.listeCoordonnees.add(i, obtenirCoordonneeLigne(this.controller.plan.listeConvoyeur.get(i) ));
        }
        
        // on trace chacune des lignes
        for (int j= 0; j< this.listeCoordonnees.size(); j++)
        {
            
            g.setColor(Color.BLUE);
            
            Graphics2D g2d = (Graphics2D) g;
            
            BasicStroke bs1 = new BasicStroke(2, BasicStroke.CAP_ROUND, BasicStroke.JOIN_BEVEL);
            g2d.setStroke(bs1);
            
            
            g2d.drawLine(this.listeCoordonnees.get(j).getX1() , this.listeCoordonnees.get(j).getY1() , this.listeCoordonnees.get(j).getX2(), this.listeCoordonnees.get(j).getY2());
        }
        
        // on vide la liste après avoir tracé toutes les lignes
        listeCoordonnees.clear();
    }
    
    public void AfficherPanneauPlanTravail(boolean estVisible)
    {
        this.setVisible(estVisible);
    }
    
    /*
    * retourne les coordonnées utilisées pour tracer la ligne représentant un convoyeur
    * @param c de type Convoyeur
    * @return coordLigne de type CoordonneeLigne
    */
    private CoordonneeLigne obtenirCoordonneeLigne(Convoyeur c)
    {
        CoordonneeLigne coordLigne = new CoordonneeLigne( c.coorDepartX(), c.coorDepartY(), c.coorArriveeX(), c.coorArriveeY());
        return coordLigne ;
    }
    
    private void afficherStations(){}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
